# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /apps/codes/cmake-3.26/bin/cmake

# The command to remove a file.
RM = /apps/codes/cmake-3.26/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/athira/dune-projects/dune-sc1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/athira/dune-projects/dune-sc1/build-cmake

# Utility rule file for doxygen_dune-sc1.

# Include any custom commands dependencies for this target.
include doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/compiler_depend.make

# Include the progress variables for this target.
include doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/progress.make

doc/doxygen/CMakeFiles/doxygen_dune-sc1: doc/doxygen/html

doc/doxygen/html: doc/doxygen/Doxyfile.in
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/athira/dune-projects/dune-sc1/build-cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building doxygen documentation. This may take a while"
	cd /home/athira/dune-projects/dune-sc1/build-cmake/doc/doxygen && /apps/codes/cmake-3.26/bin/cmake -D DOXYGEN_EXECUTABLE=/usr/bin/doxygen -P /opt/local/dune_210/dune-common-2.10.dev20221009/cmake/scripts/RunDoxygen.cmake

doc/doxygen/Doxyfile.in: /opt/local/dune_210/dune-common-2.10.dev20221009/doc/doxygen/Doxystyle
doc/doxygen/Doxyfile.in: /opt/local/dune_210/dune-common-2.10.dev20221009/doc/doxygen/doxygen-macros
doc/doxygen/Doxyfile.in: /home/athira/dune-projects/dune-sc1/doc/doxygen/Doxylocal
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/athira/dune-projects/dune-sc1/build-cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Creating Doxyfile.in"
	cd /home/athira/dune-projects/dune-sc1/build-cmake/doc/doxygen && /apps/codes/cmake-3.26/bin/cmake -D DOT_TRUE='#' -D DUNE_MOD_NAME=dune-sc1 -D DUNE_MOD_VERSION=1 -D DOXYSTYLE=/opt/local/dune_210/dune-common-2.10.dev20221009/doc/doxygen/Doxystyle -D DOXYGENMACROS=/opt/local/dune_210/dune-common-2.10.dev20221009/doc/doxygen/doxygen-macros -D DOXYLOCAL=/home/athira/dune-projects/dune-sc1/doc/doxygen/Doxylocal -D abs_top_srcdir=/home/athira/dune-projects/dune-sc1 -D srcdir=/home/athira/dune-projects/dune-sc1/doc/doxygen -D top_srcdir=/home/athira/dune-projects/dune-sc1 -P /opt/local/dune_210/dune-common-2.10.dev20221009/cmake/scripts/CreateDoxyFile.cmake

doc/doxygen/Doxyfile: doc/doxygen/Doxyfile.in
	@$(CMAKE_COMMAND) -E touch_nocreate doc/doxygen/Doxyfile

doxygen_dune-sc1: doc/doxygen/CMakeFiles/doxygen_dune-sc1
doxygen_dune-sc1: doc/doxygen/Doxyfile
doxygen_dune-sc1: doc/doxygen/Doxyfile.in
doxygen_dune-sc1: doc/doxygen/html
doxygen_dune-sc1: doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/build.make
.PHONY : doxygen_dune-sc1

# Rule to build all files generated by this target.
doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/build: doxygen_dune-sc1
.PHONY : doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/build

doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/clean:
	cd /home/athira/dune-projects/dune-sc1/build-cmake/doc/doxygen && $(CMAKE_COMMAND) -P CMakeFiles/doxygen_dune-sc1.dir/cmake_clean.cmake
.PHONY : doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/clean

doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/depend:
	cd /home/athira/dune-projects/dune-sc1/build-cmake && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/athira/dune-projects/dune-sc1 /home/athira/dune-projects/dune-sc1/doc/doxygen /home/athira/dune-projects/dune-sc1/build-cmake /home/athira/dune-projects/dune-sc1/build-cmake/doc/doxygen /home/athira/dune-projects/dune-sc1/build-cmake/doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : doc/doxygen/CMakeFiles/doxygen_dune-sc1.dir/depend

