# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /apps/codes/cmake-3.26/bin/cmake

# The command to remove a file.
RM = /apps/codes/cmake-3.26/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/athira/dune-projects/dune-graphene1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/athira/dune-projects/dune-graphene1/build-cmake

# Include any dependencies generated for this target.
include src/CMakeFiles/dune-graphene1.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include src/CMakeFiles/dune-graphene1.dir/compiler_depend.make

# Include the progress variables for this target.
include src/CMakeFiles/dune-graphene1.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/dune-graphene1.dir/flags.make

src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o: src/CMakeFiles/dune-graphene1.dir/flags.make
src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o: /home/athira/dune-projects/dune-graphene1/src/dune-graphene1.cc
src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o: src/CMakeFiles/dune-graphene1.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/athira/dune-projects/dune-graphene1/build-cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o"
	cd /home/athira/dune-projects/dune-graphene1/build-cmake/src && /apps/codes/gcc-11.4.0/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o -MF CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o.d -o CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o -c /home/athira/dune-projects/dune-graphene1/src/dune-graphene1.cc

src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.i"
	cd /home/athira/dune-projects/dune-graphene1/build-cmake/src && /apps/codes/gcc-11.4.0/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/athira/dune-projects/dune-graphene1/src/dune-graphene1.cc > CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.i

src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.s"
	cd /home/athira/dune-projects/dune-graphene1/build-cmake/src && /apps/codes/gcc-11.4.0/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/athira/dune-projects/dune-graphene1/src/dune-graphene1.cc -o CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.s

# Object files for target dune-graphene1
dune__graphene1_OBJECTS = \
"CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o"

# External object files for target dune-graphene1
dune__graphene1_EXTERNAL_OBJECTS =

src/dune-graphene1: src/CMakeFiles/dune-graphene1.dir/dune-graphene1.cc.o
src/dune-graphene1: src/CMakeFiles/dune-graphene1.dir/build.make
src/dune-graphene1: /opt/local/dune_210/dune-gmsh4-master/build-cmake/lib/libdunegmsh4.a
src/dune-graphene1: /opt/local/dune_210/dune-alugrid-2.10.dev20221009/build-cmake/lib/libdunealugrid.a
src/dune-graphene1: /opt/local/dune_210/dune-grid-2.10.dev20221009/build-cmake/lib/libdunegrid.a
src/dune-graphene1: /opt/local/dune_210/dune-geometry-2.10.dev20221009/build-cmake/lib/libdunegeometry.a
src/dune-graphene1: /opt/local/dune_210/dune-common-2.10.dev20221009/build-cmake/lib/libdunecommon.a
src/dune-graphene1: /usr/lib64/libz.so
src/dune-graphene1: /usr/local/lib64/libsuperlu.a
src/dune-graphene1: /usr/local/lib/libparmetis.a
src/dune-graphene1: /usr/local/lib/libmetis.so
src/dune-graphene1: /usr/lib64/liblapack.so.3
src/dune-graphene1: /opt/local/dune_210/dune-gmsh4-master/build-cmake/lib/libdunegmsh4.a
src/dune-graphene1: /opt/local/dune_210/dune-alugrid-2.10.dev20221009/build-cmake/lib/libdunealugrid.a
src/dune-graphene1: /opt/local/dune_210/dune-grid-2.10.dev20221009/build-cmake/lib/libdunegrid.a
src/dune-graphene1: /opt/local/dune_210/dune-geometry-2.10.dev20221009/build-cmake/lib/libdunegeometry.a
src/dune-graphene1: /opt/local/dune_210/dune-common-2.10.dev20221009/build-cmake/lib/libdunecommon.a
src/dune-graphene1: /usr/lib64/libz.so
src/dune-graphene1: /apps/compilers/intel/oneapi/tbb/2021.4.0/lib/intel64/gcc4.8/libtbb.so.12
src/dune-graphene1: /usr/lib64/liblapack.so.3
src/dune-graphene1: /usr/lib64/libblas.so.3
src/dune-graphene1: /usr/local/lib/libmetis.so
src/dune-graphene1: /opt/local/petsc-3.15.2/arch-linux-cxx-debug/lib/libmpi.so
src/dune-graphene1: src/CMakeFiles/dune-graphene1.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/athira/dune-projects/dune-graphene1/build-cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable dune-graphene1"
	cd /home/athira/dune-projects/dune-graphene1/build-cmake/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/dune-graphene1.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/dune-graphene1.dir/build: src/dune-graphene1
.PHONY : src/CMakeFiles/dune-graphene1.dir/build

src/CMakeFiles/dune-graphene1.dir/clean:
	cd /home/athira/dune-projects/dune-graphene1/build-cmake/src && $(CMAKE_COMMAND) -P CMakeFiles/dune-graphene1.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/dune-graphene1.dir/clean

src/CMakeFiles/dune-graphene1.dir/depend:
	cd /home/athira/dune-projects/dune-graphene1/build-cmake && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/athira/dune-projects/dune-graphene1 /home/athira/dune-projects/dune-graphene1/src /home/athira/dune-projects/dune-graphene1/build-cmake /home/athira/dune-projects/dune-graphene1/build-cmake/src /home/athira/dune-projects/dune-graphene1/build-cmake/src/CMakeFiles/dune-graphene1.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/dune-graphene1.dir/depend

