import tkinter as tk
from tkinter import filedialog, messagebox
import os


class NewFileHandler:
    """Manages new project and file creation for QuDSim GUI."""

    # Template geometries for common device structures
    TEMPLATES = {
        "MOSCAP": (
            "// MOSCAP Structure for QuDSim\n"
            "// Generated by QuDSim GUI\n"
            "//\n"
            "// Units: nm\n\n"
            "SetFactory(\"OpenCASCADE\");\n\n"
            "// Geometry parameters\n"
            "t_ox  = 4.0;   // Oxide thickness (nm)\n"
            "t_si  = 20.0;  // Silicon thickness (nm)\n"
            "t_gate = 5.0;  // Gate thickness (nm)\n"
            "w     = 50.0;  // Width (nm)\n\n"
            "// Mesh characteristic lengths\n"
            "lc_fine   = 0.5;  // Fine mesh at interfaces\n"
            "lc_coarse = 2.0;  // Coarse mesh in bulk\n\n"
            "// Silicon substrate\n"
            "Point(1) = {0, 0, 0, lc_coarse};\n"
            "Point(2) = {w, 0, 0, lc_coarse};\n"
            "Point(3) = {w, t_si, 0, lc_fine};\n"
            "Point(4) = {0, t_si, 0, lc_fine};\n\n"
            "Line(1) = {1, 2};\n"
            "Line(2) = {2, 3};\n"
            "Line(3) = {3, 4};\n"
            "Line(4) = {4, 1};\n\n"
            "Curve Loop(1) = {1, 2, 3, 4};\n"
            "Plane Surface(1) = {1};\n\n"
            "// Oxide layer\n"
            "Point(5) = {w, t_si + t_ox, 0, lc_fine};\n"
            "Point(6) = {0, t_si + t_ox, 0, lc_fine};\n\n"
            "Line(5) = {3, 5};\n"
            "Line(6) = {5, 6};\n"
            "Line(7) = {6, 4};\n\n"
            "Curve Loop(2) = {5, 6, 7, -3};\n"
            "Plane Surface(2) = {2};\n\n"
            "// Gate electrode\n"
            "Point(7) = {w, t_si + t_ox + t_gate, 0, lc_coarse};\n"
            "Point(8) = {0, t_si + t_ox + t_gate, 0, lc_coarse};\n\n"
            "Line(8)  = {5, 7};\n"
            "Line(9)  = {7, 8};\n"
            "Line(10) = {8, 6};\n\n"
            "Curve Loop(3) = {8, 9, 10, -6};\n"
            "Plane Surface(3) = {3};\n\n"
            "// Physical groups\n"
            "Physical Surface(\"Silicon\")  = {1};\n"
            "Physical Surface(\"Oxide\")    = {2};\n"
            "Physical Surface(\"Gate\")     = {3};\n"
            "Physical Line(\"Substrate\")   = {1};\n"
            "Physical Line(\"GateContact\") = {9};\n\n"
            "// Mesh refinement\n"
            "Mesh.Algorithm = 6;  // Frontal-Delaunay\n"
            "Mesh.ElementOrder = 1;\n"
        ),

        "GAA Nanowire": (
            "// Gate-All-Around Nanowire for QuDSim\n"
            "// Generated by QuDSim GUI\n"
            "//\n"
            "// 2D cross-section (cylindrical symmetry)\n"
            "// Units: nm\n\n"
            "SetFactory(\"OpenCASCADE\");\n\n"
            "// Parameters\n"
            "r_nw  = 2.5;   // Nanowire radius (nm)\n"
            "t_ox  = 2.0;   // Oxide thickness (nm)\n"
            "t_gate = 3.0;  // Gate thickness (nm)\n\n"
            "lc_fine   = 0.3;\n"
            "lc_coarse = 1.0;\n\n"
            "// Channel (circle)\n"
            "Disk(1) = {0, 0, 0, r_nw};\n\n"
            "// Oxide shell\n"
            "Disk(2) = {0, 0, 0, r_nw + t_ox};\n"
            "BooleanDifference{ Surface{2}; Delete; }{ Surface{1}; }\n\n"
            "// Gate shell\n"
            "Disk(3) = {0, 0, 0, r_nw + t_ox + t_gate};\n"
            "BooleanDifference{ Surface{3}; Delete; }{ Surface{1}; Surface{2}; }\n\n"
            "// Physical groups\n"
            "Physical Surface(\"Channel\") = {1};\n"
            "Physical Surface(\"Oxide\")   = {2};\n"
            "Physical Surface(\"Gate\")    = {3};\n\n"
            "// Mesh settings\n"
            "Mesh.CharacteristicLengthMin = 0.2;\n"
            "Mesh.CharacteristicLengthMax = 1.0;\n"
            "Mesh.Algorithm = 6;\n"
        ),

        "Graphene QD": (
            "// Graphene Quantum Dot for QuDSim\n"
            "// Generated by QuDSim GUI\n"
            "//\n"
            "// 2D geometry with circular confinement\n"
            "// Units: nm\n\n"
            "SetFactory(\"OpenCASCADE\");\n\n"
            "// Quantum dot parameters\n"
            "r_dot = 10.0;  // Dot radius (nm)\n"
            "lc = 0.5;      // Mesh size\n\n"
            "// Circular quantum dot\n"
            "Disk(1) = {0, 0, 0, r_dot};\n\n"
            "// Physical group\n"
            "Physical Surface(\"GrapheneDot\") = {1};\n\n"
            "// Uniform mesh\n"
            "Mesh.CharacteristicLengthMin = 0.3;\n"
            "Mesh.CharacteristicLengthMax = 0.8;\n"
            "Mesh.Algorithm = 6;\n"
        ),

        "NC Flash Memory": (
            "// Nanocrystal Flash Memory Unit Cell for QuDSim\n"
            "// Generated by QuDSim GUI\n"
            "//\n"
            "// Cylindrical coordinate system (r, z)\n"
            "// Units: nm\n\n"
            "// Parameters\n"
            "r_nc    = 2.5;   // Nanocrystal radius\n"
            "t_tunox = 4.0;   // Tunnel oxide (SiO2)\n"
            "t_nc    = 5.0;   // NC layer thickness\n"
            "t_hto1  = 4.0;   // Bottom HTO\n"
            "t_hk    = 8.0;   // High-k dielectric\n"
            "t_hto2  = 4.0;   // Top HTO\n"
            "t_sub   = 10.0;  // Substrate depth\n"
            "r_max   = 15.0;  // Radial extent\n\n"
            "lc_fine   = 0.3;\n"
            "lc_coarse = 1.5;\n\n"
            "// Substrate\n"
            "Point(1) = {0, 0, 0, lc_coarse};\n"
            "Point(2) = {r_max, 0, 0, lc_coarse};\n"
            "Point(3) = {r_max, t_sub, 0, lc_fine};\n"
            "Point(4) = {0, t_sub, 0, lc_fine};\n\n"
            "Line(1) = {1, 2};\n"
            "Line(2) = {2, 3};\n"
            "Line(3) = {3, 4};\n"
            "Line(4) = {4, 1};\n\n"
            "Curve Loop(1) = {1, 2, 3, 4};\n"
            "Plane Surface(1) = {1};\n\n"
            "Physical Surface(\"Substrate\") = {1};\n"
            "Physical Line(\"SubstrateBottom\") = {1};\n\n"
            "Mesh.Algorithm = 6;\n"
        ),

        "Empty": (
            "// QuDSim Geometry File\n"
            "// Generated by QuDSim GUI\n"
            "//\n"
            "// Define your device geometry below\n"
            "// Units: nm\n\n"
            "SetFactory(\"OpenCASCADE\");\n\n"
            "// Mesh characteristic length\n"
            "lc = 1.0;\n\n"
            "// Define points, lines, surfaces here\n"
            "// ...\n\n"
            "Mesh.Algorithm = 6;\n"
        ),
    }

    def __init__(self, app):
        self.app = app

    def new_project(self):
        """Create a new QuDSim project with a template dialog."""
        dialog = tk.Toplevel(self.app.root)
        dialog.title("New QuDSim Project")
        dialog.geometry("550x480")
        dialog.resizable(False, False)
        dialog.transient(self.app.root)
        dialog.grab_set()

        main_frame = tk.Frame(dialog, padx=20, pady=15)
        main_frame.pack(fill=tk.BOTH, expand=True)

        tk.Label(main_frame, text="Create New Project",
                 font=("Helvetica", 14, "bold"),
                 fg="#2c3e50").pack(anchor=tk.W, pady=(0, 15))

        # Project name
        name_frame = tk.Frame(main_frame)
        name_frame.pack(fill=tk.X, pady=5)
        tk.Label(name_frame, text="Project Name:",
                 font=("Helvetica", 10), width=15,
                 anchor=tk.W).pack(side=tk.LEFT)
        name_var = tk.StringVar(value="MyDevice")
        tk.Entry(name_frame, textvariable=name_var,
                 font=("Helvetica", 10), width=30).pack(
                     side=tk.LEFT, padx=(5, 0))

        # Project directory
        dir_frame = tk.Frame(main_frame)
        dir_frame.pack(fill=tk.X, pady=5)
        tk.Label(dir_frame, text="Directory:",
                 font=("Helvetica", 10), width=15,
                 anchor=tk.W).pack(side=tk.LEFT)
        dir_var = tk.StringVar(value=os.getcwd())
        dir_entry = tk.Entry(dir_frame, textvariable=dir_var,
                             font=("Helvetica", 10), width=25)
        dir_entry.pack(side=tk.LEFT, padx=(5, 5))
        tk.Button(dir_frame, text="Browse",
                  command=lambda: dir_var.set(
                      filedialog.askdirectory() or dir_var.get()
                  )).pack(side=tk.LEFT)

        # Template selection
        tk.Label(main_frame, text="Device Template:",
                 font=("Helvetica", 10, "bold"),
                 fg="#2c3e50").pack(anchor=tk.W, pady=(15, 5))

        template_var = tk.StringVar(value="MOSCAP")
        template_frame = tk.Frame(main_frame)
        template_frame.pack(fill=tk.X)

        for template_name in self.TEMPLATES:
            tk.Radiobutton(template_frame, text=template_name,
                           variable=template_var, value=template_name,
                           font=("Helvetica", 10)).pack(anchor=tk.W, pady=2)

        # Description of selected template
        desc_label = tk.Label(main_frame, text="",
                              font=("Helvetica", 9), fg="#5d6d7e",
                              wraplength=480, justify=tk.LEFT)
        desc_label.pack(anchor=tk.W, pady=(10, 5))

        descriptions = {
            "MOSCAP": "MOS capacitor structure for self-consistent Schrodinger-Poisson simulations.",
            "GAA Nanowire": "Gate-all-around nanowire cross-section for gate leakage analysis.",
            "Graphene QD": "Circular graphene quantum dot for Dirac equation solver.",
            "NC Flash Memory": "Nanocrystal flash memory unit cell in cylindrical coordinates.",
            "Empty": "Blank geometry file for custom device structures.",
        }

        def update_desc(*args):
            desc_label.config(text=descriptions.get(template_var.get(), ""))
        template_var.trace_add("write", update_desc)
        update_desc()

        # Buttons
        btn_frame = tk.Frame(main_frame)
        btn_frame.pack(fill=tk.X, pady=(20, 0))

        tk.Button(btn_frame, text="Create Project",
                  font=("Helvetica", 10, "bold"),
                  bg="#2e6da4", fg="white", width=15,
                  command=lambda: self._create_project(
                      name_var.get(), dir_var.get(),
                      template_var.get(), dialog)
                  ).pack(side=tk.LEFT, padx=5)
        tk.Button(btn_frame, text="Cancel",
                  font=("Helvetica", 10), width=10,
                  command=dialog.destroy).pack(side=tk.RIGHT, padx=5)

    def _create_project(self, name, directory, template, dialog):
        """Create project files on disk."""
        if not name.strip():
            messagebox.showwarning("Invalid Name",
                                   "Please enter a project name.")
            return

        # Create project directory
        project_dir = os.path.join(directory, name.replace(" ", "_"))
        os.makedirs(project_dir, exist_ok=True)
        os.makedirs(os.path.join(project_dir, "results"), exist_ok=True)

        # Write .geo file from template
        geo_path = os.path.join(project_dir, name.replace(" ", "_") + ".geo")
        template_content = self.TEMPLATES.get(template, self.TEMPLATES["Empty"])
        with open(geo_path, "w") as f:
            f.write(template_content)

        # Update app state
        self.app.project_name.set(name)
        self.app.current_geo_file = geo_path
        self.app.update_status(
            "Project created: {}".format(name))

        dialog.destroy()

        # Open the .geo file in editor
        self.app.load_handler._load_geo(geo_path)

        messagebox.showinfo(
            "Project Created",
            "Project '{}' created successfully at:\n{}\n\n"
            "The geometry file has been opened for editing.".format(
                name, project_dir))
