# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# compile CXX with /apps/codes/gcc-11.4.0/bin/g++
CXX_DEFINES = -DENABLE_MPI=1 -DENABLE_QUADMATH=1 -DENABLE_SUPERLU=1 -DENABLE_TBB=1 -DHAVE_CONFIG_H -DMETIS_API_VERSION=5 -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_GLIBCXX_USE_FLOAT128

CXX_INCLUDES = -I/home/athira/dune-projects/dune-sc1/build-cmake -I/home/athira/dune-projects/dune-sc1 -I/opt/local/dune_210/dune-common-2.10.dev20221009 -I/opt/local/dune_210/dune-geometry-2.10.dev20221009 -I/opt/local/dune_210/dune-grid-2.10.dev20221009 -I/opt/local/dune_210/dune-istl-2.10.dev20221009 -I/opt/local/dune_210/dune-alugrid-2.10.dev20221009 -I/opt/local/dune_210/dune-gmsh4-master -I/opt/local/dune_210/dune-grid-howto-master -I/opt/local/dune_210/dune-localfunctions-2.10.dev20221009 -isystem /apps/compilers/intel/oneapi/tbb/2021.4.0/include -isystem /opt/local/metis-5.1.0/include -isystem /opt/local/parmetis-4.0.3/include

CXX_FLAGS = -std=c++17 /opt/local/petsc-3.15.2/arch-linux-cxx-debug/lib/libpetsc.so.3.15 /opt/local/slepc-3.15.2/arch-linux-cxx-debug/lib/libslepc.so.3.15 -fPIE -pthread -fext-numeric-literals

